Feature: Test Sprint 10 story DBMTE-30

@manual @DEBD-181
Scenario Outline: My Address Book - Adding New Address Pages :Scenario-New User - Add new address:Find Address -Case1:Recognized for 1 address
  Given I logout
  When I click on "tab2" on "loginPage"
  And I enter "<email>" in "emailAddressFieldCreateAccount" on "loginPage"
  And I click on "createAccountButton" on "loginPage"
  When I should see "headerText" as "Create an account" on "registerPage"
  Then I enter "<firstName>" in "firstNameField" on "registerPage"
  And I enter "<lastname>" in "lastNamefield" on "registerPage"
  And I enter "<password>" in "passwordField" on "registerPage"
  And I click on "createAccountButton" on "registerPage"
  Then I click on "menuIcon" on "commonPage"
  And I click on "My Account" position "6"
  And I should see "titleOfPage" as "My Account" on "my-details"
  And I should see "myAddressBook" exist on "my-details"
  And I click on "myAddressBook" on "my-details"
  And I should see "titleOfPage" as "My address book" on "my-details"
  When I should see "addNewAddressButton" exist on "my-details"
  And I click on "addNewAddressButton" on "my-details"
  And I should see "titleOfPage" as "Add a new address" on "address-book"
  And I should see "title" exist on "address-book"
  And I should see "firstName" exist on "address-book"
  And I should see "lastName" exist on "address-book"
  And I should see "phoneNumber" exist on "address-book"
  And I should see "emailAddressField" exist on "address-book"
  And I should see "houseNumber" exist on "address-book"
  And I should see "country" exist on "address-book"
  And I should see "postcode" exist on "address-book"
  And I should see "findYourAddressButton" exist on "address-book"
  And I should see "enterAddressManuallyLink" exist on "address-book"
  And I should see "cancelButton" exist on "address-book"
  And I should see "addAddressButton" exist on "address-book"

@manual @DEBD-181
Scenario Outline: My Address Book - Adding New Address Pages :Scenario-Add new address:Find Address -Case1:Recognized for 1 address
  When I should see "titleOfPage" as "Add a new address" on "address-book"
  Then I enter "<firstName>" in "firstName" on "address-book"
  And I enter "<lastname>" in "lastName" on "address-book"
  And I enter "<phoneNumber>" in "phoneNumber" on "address-book"
  And I enter "<housenumber>" in "houseNumber" on "address-book"
  And I enter "<postcode>" in "postcode" on "address-book"
  Then I click on "findYourAddressButton" on "address-book"
  And I should see "foundAddress" exist on "address-book"
  And I verify that "houseNumber" is disabled
  And I should see "editButton" exist on "address-book"
  Then I click on "editButton" on "address-book"
  And I verify that "houseNumber" is editable
  Then I click on "addAddressButton" on "address-book"

@manual @DEBD-181
Scenario Outline: My Address Book - Adding New Address Pages :Scenario-Add new address:Find Address -Case2:Drop down when Input options Not Recognized
  When I should see "addNewAddressButton" exist on "my-details"
  And I click on "addNewAddressButton" on "my-details"
  And I should see "titleOfPage" as "Add a new address" on "address-book"
  Then I enter "<firstName>" in "firstName" on "address-book"
  And I enter "<lastname>" in "lastName" on "address-book"
  And I enter "<phoneNumber>" in "phoneNumber" on "address-book"
  And I enter "<housenumber>" in "houseNumber" on "address-book"
  And I enter "<postcode>" in "postcode" on "address-book"
  Then I click on "findYourAddressButton" on "address-book"
  And I should see "findAnAddressPopUp" exist on "address-book"
  And I select address from dropdown on "address-book"
  And click on "continueButton" on "address-book"
  Then I verify that "houseNumber" is disabled
  And I should see "editButton" exist on "address-book"
  Then I click on "editButton" on "address-book"
  And I verify that "houseNumber" is editable
  Then I click on "addAddressButton" on "address-book"

@manual @DEBD-181
Scenario Outline: My Address Book - Adding New Address Pages :Scenario-Add new address:Manual Address entry
  When I should see "addNewAddressButton" exist on "my-details"
  And I click on "addNewAddressButton" on "my-details"
  And I should see "titleOfPage" as "Add a new address" on "address-book"
  Then I enter "<firstName>" in "firstName" on "address-book"
  And I enter "<lastname>" in "lastName" on "address-book"
  And I enter "<phoneNumber>" in "phoneNumber" on "address-book"
  And I enter "<housenumber>" in "houseNumber" on "address-book"
  Then I click on "enterAddressManuallyLink" on "address-book"
  And I should see "addressLine1" exist on "address-book"
  And I should see "addressLine2" exist on "address-book"
  And I should see "city" exist on "address-book"
  And I should see "county" exist on "address-book"
  And I should see "postcodeManual" exist on "address-book"
  And I should see "findAnotherAddressLink" exist on "address-book"
  And I should see "bfpoLink" exist on "address-book"
  And I should see "clearAddressButton" exist on "address-book"
  Then I click on "bfpoLink" on "address-book"
  And I should see "bfpoPopUp" exist on "address-book"
  And I click on "closebutton" on "address-book"
  Then I click on "addAddressButton" on "address-book"

@manual @DEBD-181
Scenario Outline: My Address Book - Adding New Address Pages :Scenario-Add new address page:Find another address functionality
  When I should see "addNewAddressButton" exist on "my-details"
  And I click on "addNewAddressButton" on "my-details"
  And I should see "titleOfPage" as "Add a new address" on "address-book"
  Then I enter "<firstName>" in "firstName" on "address-book"
  And I enter "<lastname>" in "lastName" on "address-book"
  And I enter "<phoneNumber>" in "phoneNumber" on "address-book"
  And I enter "<housenumber>" in "houseNumber" on "address-book"
  Then I click on "enterAddressManuallyLink" on "address-book"
  And I should see "addressLine1" exist on "address-book"
  And I should see "addressLine2" exist on "address-book"
  And I should see "city" exist on "address-book"
  And I should see "county" exist on "address-book"
  And I should see "postcodeManual" exist on "address-book"
  Then I click on "findAnotherAddressLink" on "address-book"
  And I should not see "addressLine1" on "address-book"
  And I should not see "addressLine2" on "address-book"
  And I should not see "city" on "address-book"
  And I should not see "county" on "address-book"

@manual @DEBD-181
Scenario Outline: My Address Book - Adding New Address Pages :Scenario-Add new address page:Clear address functionality
  When I should see "addNewAddressButton" exist on "my-details"
  And I click on "addNewAddressButton" on "my-details"
  And I should see "titleOfPage" as "Add a new address" on "address-book"
  Then I enter "<firstName>" in "firstName" on "address-book"
  And I enter "<lastname>" in "lastName" on "address-book"
  And I enter "<phoneNumber>" in "phoneNumber" on "address-book"
  And I enter "<housenumber>" in "houseNumber" on "address-book"
  Then I click on "enterAddressManuallyLink" on "address-book"
  And I should see "addressLine1" exist on "address-book"
  And I should see "addressLine2" exist on "address-book"
  And I should see "city" exist on "address-book"
  And I should see "county" exist on "address-book"
  And I should see "postcodeManual" exist on "address-book"
  Then I click on "clearAddressButton" on "address-book"
  And I should see "clearAddresspopUp" as "Are you sure you want to reset / clear all information ?" on "address-book"
  And I click on "yesButton" on "address-book"
  Then I should see "firstName" as "null" on "address-book"
  And I should see "lastName" as "null" on "address-book"
  And I should see "phoneNumber" as "null" on "address-book"
  And I should see "houseNumber" as "null" on "address-book"
